# run backend pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
  namespace: pipeline
  labels:
    app: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
      tier: backend 
      track: stable
  template:
    metadata:
      labels:
        app: pipeline 
        tier: backend 
        track: stable
    spec:
      containers:
      - name: backend-container
        image: backend-app:1.4
        ports:
        - name: http
          containerPort: 8080