# run backend pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline
      tier: backend 
  template:
    metadata:
      labels:
        app: pipeline 
        tier: backend 
        track: stable
    spec:
      containers:
      - name: backend-container
        image: backend 
        ports:
        - name: http
          containerPort: 8080