# runs frontend pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
      tier: frontend
  template:
    metadata:
      labels:
        app: pipeline 
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: frontend:2.0 
        lifecycle:
          preStop:
            exec:
              command: ["nginx","-s","quit"]  # tells NGINX to shutdown
