upstream pipeline-api {
    server backend;
}

server {
    listen 80;
    
    location / {
        # The following statement will proxy traffic to the upstream named Backend
        proxy_pass http://pipeline-api.com;
    }
}