upstream pipeline-api {
    server backend-service:8080;
}

server {
    listen 80;
    listen [::]:80;

    # route to frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # route to backend-service
    location /api/ {
        # proxy traffic to the upstream 
        proxy_pass http://pipeline-api; 
    }
}