upstream pipeline-api {
    server backend-deployment;
}

server {
    listen 8080;
    
    location / {
        # The following statement will proxy traffic to the upstream named Backend
        proxy_pass http://pipeline-api.com;
    }
}